// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: nephelo

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Main
void ui_Main_screen_init(void);
lv_obj_t * ui_Main;
lv_obj_t * ui_Container1;
lv_obj_t * ui_time;
lv_obj_t * ui_weather;
lv_obj_t * ui_temperature;
lv_obj_t * ui_geolocation;


// SCREEN: ui_Conn
void ui_Conn_screen_init(void);
lv_obj_t * ui_Conn;
lv_obj_t * ui_Container2;
lv_obj_t * ui_status;
lv_obj_t * ui_Image2;


// SCREEN: ui_ConnFailed
void ui_ConnFailed_screen_init(void);
lv_obj_t * ui_ConnFailed;
lv_obj_t * ui_Container3;
lv_obj_t * ui_status1;
lv_obj_t * ui_Image1;


// SCREEN: ui_Sync
void ui_Sync_screen_init(void);
lv_obj_t * ui_Sync;
lv_obj_t * ui_Container4;
lv_obj_t * ui_status2;
lv_obj_t * ui_Image3;


// SCREEN: ui_ota
void ui_ota_screen_init(void);
lv_obj_t * ui_ota;
lv_obj_t * ui_Container5;
lv_obj_t * ui_status3;
lv_obj_t * ui_Image4;
lv_obj_t * ui____initial_actions0;
const lv_image_dsc_t * ui_imgset_1839397126[1] = {&ui_img_1381597115};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Main_screen_init();
    ui_Conn_screen_init();
    ui_ConnFailed_screen_init();
    ui_Sync_screen_init();
    ui_ota_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Main);
}
