// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: nephelo

#ifndef _NEPHELO_UI_H
#define _NEPHELO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_weather;
extern lv_obj_t * ui_temperature;
extern lv_obj_t * ui_geolocation;
// SCREEN: ui_Conn
void ui_Conn_screen_init(void);
extern lv_obj_t * ui_Conn;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_status;
extern lv_obj_t * ui_Image2;
// SCREEN: ui_ConnFailed
void ui_ConnFailed_screen_init(void);
extern lv_obj_t * ui_ConnFailed;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_status1;
extern lv_obj_t * ui_Image1;
// SCREEN: ui_Sync
void ui_Sync_screen_init(void);
extern lv_obj_t * ui_Sync;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_status2;
extern lv_obj_t * ui_Image3;
// SCREEN: ui_ota
void ui_ota_screen_init(void);
extern lv_obj_t * ui_ota;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_status3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_753710586);    // assets/ic--baseline-wifi-find.png
LV_IMG_DECLARE(ui_img_982888080);    // assets/ic--outline-signal-wifi-bad.png
LV_IMG_DECLARE(ui_img_1444199796);    // assets/mdi--database-sync.png
LV_IMG_DECLARE(ui_img_588753852);    // assets/ic--round-cloud-download.png
LV_IMG_DECLARE(ui_img_1381597115);    // assets/ic--outline-signal-wifi-statusbar-connected-no-internet-4.png



LV_FONT_DECLARE(ui_font_autl21);
LV_FONT_DECLARE(ui_font_lon21);
LV_FONT_DECLARE(ui_font_panel36);
LV_FONT_DECLARE(ui_font_panl36);
LV_FONT_DECLARE(ui_font_panm36);
LV_FONT_DECLARE(ui_font_spgb38);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
