// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: nephelo

#include "ui.h"

void ui_Conn_screen_init(void)
{
    ui_Conn = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Conn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container2 = lv_obj_create(ui_Conn);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 240);
    lv_obj_set_height(ui_Container2, 240);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_status = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_status, LV_SIZE_CONTENT);   /// 0
    lv_obj_set_height(ui_status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_status, 0);
    lv_obj_set_y(ui_status, 35);
    lv_obj_set_align(ui_status, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_status, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_status, "Connecting");
    lv_obj_set_style_text_letter_space(ui_status, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_status, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_status, &ui_font_lon21, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_Conn);
    lv_image_set_src(ui_Image2, &ui_img_753710586);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image2, 0);
    lv_obj_set_y(ui_Image2, -20);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
