// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: nephelo

#include "ui.h"

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 240);
    lv_obj_set_height(ui_Container1, 240);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 0
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, 0);
    lv_obj_set_y(ui_time, -50);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_time, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_time, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_long_mode(ui_time, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_time, "22:34");
    ui_object_set_themeable_style_property(ui_time, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Lavander);
    ui_object_set_themeable_style_property(ui_time, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Lavander);
    lv_obj_set_style_text_letter_space(ui_time, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_time, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_time, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time, &ui_font_spgb38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_weather, LV_SIZE_CONTENT);   /// 0
    lv_obj_set_height(ui_weather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weather, 0);
    lv_obj_set_y(ui_weather, 35);
    lv_obj_set_align(ui_weather, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_weather, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_weather, "Weather Description");
    ui_object_set_themeable_style_property(ui_weather, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Lavander);
    ui_object_set_themeable_style_property(ui_weather, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Lavander);
    lv_obj_set_style_text_letter_space(ui_weather, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_weather, -5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_weather, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weather, &ui_font_lon21, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temperature = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_temperature, LV_SIZE_CONTENT);   /// 0
    lv_obj_set_height(ui_temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperature, 0);
    lv_obj_set_y(ui_temperature, 70);
    lv_obj_set_align(ui_temperature, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_temperature, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_temperature, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_long_mode(ui_temperature, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_temperature, "32°C 64%");
    ui_object_set_themeable_style_property(ui_temperature, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Lavander);
    ui_object_set_themeable_style_property(ui_temperature, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Lavander);
    lv_obj_set_style_text_letter_space(ui_temperature, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_temperature, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_temperature, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temperature, &ui_font_lon21, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_geolocation = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_geolocation, LV_SIZE_CONTENT);   /// 0
    lv_obj_set_height(ui_geolocation, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_geolocation, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_geolocation, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_geolocation, "Guoxiang, Jiangsu");
    ui_object_set_themeable_style_property(ui_geolocation, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Lavander);
    ui_object_set_themeable_style_property(ui_geolocation, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Lavander);
    lv_obj_set_style_text_letter_space(ui_geolocation, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_geolocation, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_geolocation, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_geolocation, &ui_font_lon21, LV_PART_MAIN | LV_STATE_DEFAULT);

}
