// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: nephelo

#include "ui.h"

void ui_Sync_screen_init(void)
{
    ui_Sync = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Sync, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container4 = lv_obj_create(ui_Sync);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 240);
    lv_obj_set_height(ui_Container4, 240);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_status2 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_status2, LV_SIZE_CONTENT);   /// 0
    lv_obj_set_height(ui_status2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_status2, 0);
    lv_obj_set_y(ui_status2, 35);
    lv_obj_set_align(ui_status2, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_status2, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_status2, "Fetching Data");
    lv_obj_set_style_text_letter_space(ui_status2, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_status2, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_status2, &ui_font_lon21, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_image_create(ui_Sync);
    lv_image_set_src(ui_Image3, &ui_img_1444199796);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image3, 0);
    lv_obj_set_y(ui_Image3, -20);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
