// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: nephelo

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_Pink[1] = {0xFFB3D5};
const ui_theme_variable_t _ui_theme_alpha_Pink[1] = {255};

const ui_theme_variable_t _ui_theme_color_Lavander[1] = {0xE2A8FF};
const ui_theme_variable_t _ui_theme_alpha_Lavander[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

